version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=universityfree
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

